import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import '../../styles/ClientesAdmin.css';
import apiClient from '../../../api/apiClient'; // RUTA CORREGIDA

const API_CLIENTES_URL = '/admin/users/clientes'; // Endpoint para obtener clientes
const API_USERS_BASE_URL = '/admin/users'; // Endpoint base para operaciones CRUD de usuarios

const ClientesAdmin = () => {

  const navigate = useNavigate();
  const [clientes, setClientes] = useState([]); // Stores fetched clients
  const [mostrarModalBusqueda, setMostrarModalBusqueda] = useState(false); // Search client modal
  const [mostrarModalResultado, setMostrarModalResultado] = useState(false); // Search result modal
  const [mostrarModalEdicion, setMostrarModalEdicion] = useState(false); // Edit client modal
  const [clienteEditando, setClienteEditando] = useState(null);
  const [busquedaCliente, setBusquedaCliente] = useState({
    id: ''
  });
  const [clienteEncontrado, setClienteEncontrado] = useState(null);
  const [errores, setErrores] = useState({});
  const [loading, setLoading] = useState(true); // Loading state for API calls
  const [error, setError] = useState(null); // Error state for API calls

  // Function to fetch all clients from the backend
  const fetchClientes = async (query = '') => { // Added query parameter
    setLoading(true);
    setError(null);
    try {
      const url = query ? `${API_CLIENTES_URL}?query=${encodeURIComponent(query)}` : API_CLIENTES_URL;
      const response = await apiClient(url);

      // Manejar específicamente el estado 204 No Content
      if (response.status === 204) {
        setClientes([]); // No hay clientes, establecer una lista vacía
        return; // Salir de la función, no hay JSON que parsear
      }
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      // Map backend User fields to frontend Cliente fields
      const mappedClients = data.map(user => {
        // Usar user.nombre y user.apellido directamente del backend
        const nombre = user.nombre || '';
        const apellido = user.apellido || '';
        return {
          id: user.id_usuario, // Map id_usuario to id
          nombre: nombre,
          apellido: apellido,
          email: user.correo,
          direccion: user.direccion,
          celular: user.telefono, // Map telefono to celular
          
        };
      });
      setClientes(mappedClients);
    } catch (err) {
      console.error("Error fetching clients:", err);
      setError("Error al cargar los clientes. Intente de nuevo más tarde.");
      alert(`Error al cargar clientes: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => {
    fetchClientes();
  }, []);

  const handleEditInputChange = (e) => {
    const { name, value } = e.target;
    setClienteEditando(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleEditar = () => {
    setClienteEditando({...clienteEncontrado});
    setMostrarModalResultado(false);
    setMostrarModalEdicion(true);
  };
  
  const handleCancelarEdicion = () => {
    setMostrarModalEdicion(false);
    setClienteEditando(null);
    setErrores({});
  };


   const validarFormulario = (clienteData, isEdit = false) => {
    const nuevosErrores = {};
    
    // For new clients, ID is auto-generated by backend, so no frontend ID validation
    // For editing, ID is read-only, so no validation needed here.
    
    if (!clienteData.nombre.trim()) {
      nuevosErrores.nombre = 'El nombre es requerido';
    }
    
    if (!clienteData.apellido.trim()) {
      nuevosErrores.apellido = 'El apellido es requerido';
    }
    
    if (!clienteData.email.trim()) {
      nuevosErrores.email = 'El email es requerido';
    } else if (!/\S+@\S+\.\S/.test(clienteData.email)) {
      nuevosErrores.email = 'El formato de email no es válido';
    }
    
    if (!clienteData.direccion.trim()) {
      nuevosErrores.direccion = 'La dirección es requerida';
    }
    
    if (!clienteData.celular.trim()) {
      nuevosErrores.celular = 'El celular es requerido';
    } else if (!/^\d{9}$/.test(clienteData.celular)) {
      nuevosErrores.celular = 'El celular debe tener 9 dígitos';
    }

    if (!isEdit && !clienteData.password.trim()) { // Password required only for new clients
      nuevosErrores.password = 'La contraseña es requerida';
    }
    
    setErrores(nuevosErrores);
    return Object.keys(nuevosErrores).length === 0;
  };

  const handleGuardarEdicion = async () => {
    if (validarFormulario(clienteEditando, true)) { // Pass true for isEdit
      const userToUpdate = {
        nombre: clienteEditando.nombre, // Enviar nombre por separado
        apellido: clienteEditando.apellido, // Enviar apellido por separado
        correo: clienteEditando.email,
        telefono: clienteEditando.celular,
        direccion: clienteEditando.direccion,
        // password and estado are not typically updated via this form,
        // assuming backend handles them or they are not changed.
        // If password needs to be updated, a separate field would be needed.
      };

      try {
        const response = await apiClient(`${API_USERS_BASE_URL}/${clienteEditando.id}`, {
          method: 'PUT',
          body: JSON.stringify(userToUpdate),
        });

        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.message || `HTTP error! status: ${response.status}`);
        }

        alert('Cliente actualizado con éxito!');
        fetchClientes(); // Re-fetch all clients to update the table
        setMostrarModalEdicion(false);
        setClienteEditando(null);
        setErrores({});
      } catch (err) {
        console.error("Error updating client:", err);
        alert(`Error al actualizar el cliente: ${err.message}`);
      }
    }
  };

  const handleEliminarCliente = async () => {
    if (window.confirm(`¿Está seguro que desea eliminar al cliente ${clienteEncontrado.nombre} ${clienteEncontrado.apellido}?`)) {
      try {
        const response = await apiClient(`${API_USERS_BASE_URL}/${clienteEncontrado.id}`, {
          method: 'DELETE',
        });

        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.message || `HTTP error! status: ${response.status}`);
        }

        alert('Cliente eliminado con éxito!');
        fetchClientes(); // Re-fetch all clients to update the table
        setMostrarModalResultado(false);
        setClienteEncontrado(null);
      } catch (err) {
        console.error("Error deleting client:", err);
        alert(`Error al eliminar el cliente: ${err.message}`);
      }
    }
  };

  const handleGuardarCambios = () => {
    // This button now acts as a "Refresh Data" button, as CUD operations are immediate.
    fetchClientes();
    alert('Datos actualizados desde el servidor.');
  };
  const handleBuscarClick = () => {
    setMostrarModalBusqueda(true);
    setBusquedaCliente({ id: '' }); // Clear previous search ID
    setErrores({}); // Clear errors
  };

  const handleCancelarBusqueda = () => {
    setMostrarModalBusqueda(false);
    setBusquedaCliente({
      id: ''
    });
     setErrores({});
  };

  const handleBuscarCliente = async () => {
    if (!busquedaCliente.id.trim()) {
      setErrores({ id: 'Ingrese un código para buscar.' });
      return;
    }
    setErrores({}); // Clear previous errors

    try {
      const response = await apiClient(`${API_USERS_BASE_URL}/${busquedaCliente.id}`);
      if (response.status === 404) {
        alert('No se encontró ningún cliente con ese código.');
        setClienteEncontrado(null);
      } else if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || `HTTP error! status: ${response.status}`);
      } else {
        const data = await response.json();
        // Usar data.nombre y data.apellido directamente
        const nombre = data.nombre || '';
        const apellido = data.apellido || '';
        setClienteEncontrado({
          id: data.id_usuario,
          nombre: nombre,
          apellido: apellido,
          email: data.correo,
          direccion: data.direccion,
          celular: data.telefono,
          
        });
        setMostrarModalBusqueda(false);
        setMostrarModalResultado(true);
      }
    } catch (err) {
      console.error("Error searching client:", err);
      alert(`Error al buscar el cliente: ${err.message}`);
      setClienteEncontrado(null);
    }
  };

  const handleVolverABusqueda = () => {
    setMostrarModalResultado(false);
    setMostrarModalBusqueda(true);
  };

  const handleCerrarResultado = () => {
    setMostrarModalResultado(false);
    setBusquedaCliente({
      id: ''
    });
    setClienteEncontrado(null);
  };
  const handleSalir = () => {
    navigate('/admin/dashboard');
  };

  const handleBusquedaRapida = (e) => {
    const query = e.target.value.toLowerCase();  
    fetchClientes(query);
  };

  return (
    <div className="page-container-for-fixed-nav">
      <Navbar />
      
      <div className="clientes-admin-container">
        <div className="clientes-header">
          <h1>Mantenimiento de Clientes</h1>
            <div className="clientes-acciones">
            <button className="btn-accion btn-buscar" onClick={handleBuscarClick}>BUSCAR CLIENTE</button>
            <button 
              className="btn-accion btn-guardar" 
              onClick={handleGuardarCambios}
            >
              ACTUALIZA DATOS
            </button>
            <button className="btn-accion btn-salir" onClick={handleSalir}>SALIR</button>
          </div>
        </div>

        {/* Modal de Búsqueda */}
        {mostrarModalBusqueda && (
          <div className="modal-overlay">
            <div className="modal-content modal-busqueda">
              <div className="modal-header">
                <h2>Buscar Cliente</h2>
                <button className="close-button" onClick={handleCancelarBusqueda}>&times;</button>
              </div>
              <div className="form-busqueda">
                <div className="form-group">
                  <label>Código Cliente</label>
                  <input
                    type="text"
                    value={busquedaCliente.id}
                    onChange={(e) => setBusquedaCliente(prev => ({...prev, id: e.target.value}))}
                    placeholder="Ingreso el código del cliente"
                  />
                </div>
                <div className="modal-buttons">
                  <button onClick={handleCancelarBusqueda} className="btn-cancelar">Cancelar</button>
                  <button onClick={handleBuscarCliente} className="btn-buscar">Buscar</button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Modal de Resultado de Búsqueda */}
        {mostrarModalResultado && clienteEncontrado && (
          <div className="modal-overlay">
            <div className="modal-content modal-resultado">
              <div className="modal-header">
                <h2>Cliente Buscado</h2>
                <button className="close-button" onClick={handleCerrarResultado}>&times;</button>
              </div>
              <div className="form-grid">
                <div className="form-column">
                  <div className="form-group">
                    <label>Código</label>
                    <input
                      type="text"
                      value={clienteEncontrado.id}
                      readOnly
                    />
                  </div>
                  <div className="form-group">
                    <label>Nombre</label>
                    <input
                      type="text"
                      value={clienteEncontrado.nombre}
                      readOnly
                    />
                  </div>
                  <div className="form-group">
                    <label>Apellido</label>
                    <input
                      type="text"
                      value={clienteEncontrado.apellido}
                      readOnly
                    />
                  </div>
                </div>
                <div className="form-column">
                  <div className="form-group">
                    <label>Email</label>
                    <input
                      type="text"
                      value={clienteEncontrado.email}
                      readOnly
                    />
                  </div>
                  <div className="form-group">
                    <label>Dirección</label>
                    <input
                      type="text"
                      value={clienteEncontrado.direccion}
                      readOnly
                    />
                  </div>
                  <div className="form-group">
                    <label>Celular</label>
                    <input
                      type="text"
                      value={clienteEncontrado.celular}
                      readOnly
                    />
                  </div>
                </div>
              </div>
              <div className="modal-buttons busqueda-buttons">
                <button onClick={handleVolverABusqueda} className="btn-volver">
                  <span className="flecha-back">←</span> Volver
                </button>                <div>
                  <button className="btn-eliminar" onClick={handleEliminarCliente}>Eliminar</button>
                  <button className="btn-editar" onClick={handleEditar}>Editar</button>
                </div>
              </div>
            </div>
          </div>
        )}
        {loading && (
          <div className="loading-overlay">
            <div className="loading-spinner"></div>
            <p>Cargando clientes...</p>
          </div>
        )}

        {error && (
          <div className="error-message-banner">
            <p>{error}</p>
            <button onClick={() => fetchClientes()}>Reintentar</button>
          </div>
        )}

        <div className="clientes-content">          <div className="clientes-busqueda">
            <div className="busqueda-container">
              <label>Buscar Clientes:</label>
              <div className="busqueda-input">
                <input 
                  id="quick-search"
                  type="text" 
                  placeholder="Ingrese código, nombre o apellido del cliente"
                  onChange={handleBusquedaRapida}
                />
              </div>
            </div>
          </div>

          <div className="clientes-tabla">
            <table>
              <thead>
                <tr>
                  <th>Cód</th>
                  <th>Nombre</th>
                  <th>Apellido</th>
                  <th>E-mail</th>
                  <th>Dirección</th>
                  <th>Celular</th>
                  
                </tr>
              </thead>
              <tbody>
                {clientes.length > 0 ? (
                  clientes.map(cliente => (
                    <tr key={cliente.id}>
                      <td>{cliente.id}</td>
                      <td>{cliente.nombre}</td>
                      <td>{cliente.apellido}</td>
                      <td>{cliente.email}</td>
                      <td>{cliente.direccion}</td>
                      <td>{cliente.celular}</td>
                      
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="7" style={{ textAlign: 'center' }}>No hay clientes para mostrar.</td>
                  </tr>
                )}
                </tbody>
            </table>
          </div>
        </div>

        {/* Modal de Edición de Cliente */}
        {mostrarModalEdicion && clienteEditando && (
          <div className="modal-overlay">
            <div className="modal-content">
              <h2>Editar Cliente</h2>
              <hr className="divisor" />
              <div className="form-grid">
                <div className="form-column">
                  <div className="form-group">
                    <label>Código</label>
                    <input
                      id="edit-client-id"
                      type="text"
                      name="id"
                      value={clienteEditando.id}
                      readOnly
                      className={errores.id ? 'input-error' : ''}
                    />
                    {errores.id && <span className="error-message">{errores.id}</span>}
                  </div>
                  <div className="form-group">
                    <label>Nombre</label>
                    <input
                      id="edit-client-nombre"
                      type="text"
                      name="nombre"
                      value={clienteEditando.nombre}
                      onChange={handleEditInputChange}
                      className={errores.nombre ? 'input-error' : ''}
                    />
                    {errores.nombre && <span className="error-message">{errores.nombre}</span>}
                  </div>
                  <div className="form-group">
                    <label>Apellido</label>
                    <input
                      id="edit-client-apellido"
                      type="text"
                      name="apellido"
                      value={clienteEditando.apellido}
                      onChange={handleEditInputChange}
                      className={errores.apellido ? 'input-error' : ''}
                    />
                    {errores.apellido && <span className="error-message">{errores.apellido}</span>}
                  </div>
                </div>
                <div className="form-column">
                  <div className="form-group">
                    <label>Email</label>
                    <input
                      id="edit-client-email"
                      type="email"
                      name="email"
                      value={clienteEditando.email}
                      onChange={handleEditInputChange}
                      className={errores.email ? 'input-error' : ''}
                    />
                    {errores.email && <span className="error-message">{errores.email}</span>}
                  </div>
                  <div className="form-group">
                    <label>Dirección</label>
                    <input
                      id="edit-client-direccion"
                      type="text"
                      name="direccion"
                      value={clienteEditando.direccion}
                      onChange={handleEditInputChange}
                      className={errores.direccion ? 'input-error' : ''}
                    />
                    {errores.direccion && <span className="error-message">{errores.direccion}</span>}
                  </div>
                  <div className="form-group">
                    <label>Celular</label>
                    <input
                      id="edit-client-celular"  
                      type="text"
                      name="celular"
                      value={clienteEditando.celular}
                      onChange={handleEditInputChange}
                      className={errores.celular ? 'input-error' : ''}
                      maxLength="9"
                    />
                    {errores.celular && <span className="error-message">{errores.celular}</span>}
                  </div>
                </div>
              </div>
              <div className="modal-buttons">
                <button onClick={handleCancelarEdicion} className="btn-cancelar">Cancelar</button>
                <button onClick={handleGuardarEdicion} className="btn-guardar">Guardar Cambios</button>
              </div>
            </div>
          </div>
        )}
      </div>

      <Footer />
    </div>
  );
};
export default ClientesAdmin;
